### ISSUE TITLE
Starting the Program

### ISSUE THREAD

**Issue by Jstraws** [jKi-joe/d2-item-find-notify#1]
When I try to start the application it spits out this error:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-07-05 10:42:18.632 ERROR 19696 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        at net.joe.itemfindnotifier.ItemFindNotifierApplication.main(ItemFindNotifierApplication.java:54) [classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_171]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [item-find-notifier.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [item-find-notifier.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [item-find-notifier.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [item-find-notifier.jar:1.0.0]
Caused by: java.nio.file.NoSuchFileException: \ItemLog.txt
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.newInputStream(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.lines(Unknown Source) ~[na:1.8.0_171]
        at java.nio.file.Files.lines(Unknown Source) ~[na:1.8.0_171]
        at net.joe.itemfindnotifier.service.ItemParser.parseItems(ItemParser.java:30) ~[classes!/:1.0.0]
        at net.joe.itemfindnotifier.service.DbPopulator.populate(DbPopulator.java:25) ~[classes!/:1.0.0]
        at net.joe.itemfindnotifier.ItemFindNotifierApplication.run(ItemFindNotifierApplication.java:59) [classes!/:1.0.0]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
        ... 13 common frames omitted
```

**Comment by jKi-joe** [comment]
You probably didn't configure a folder where to look for the ItemLog.txt. See step 4 under https://github.com/jKi-joe/d2-item-find-notify/blob/master/README.md#how-to-setup

**Comment by Jstraws** [comment]
Hadn't edited path correctly.

**Comment by jKi-joe** [comment]
Sure no problem :)
